# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'gluster'
    static_configs:
    - targets: ['10.211.106.76:9189']

  - job_name: 'kafka-exporter'
    static_configs:
    - targets: ['10.237.50.154:9308']

  - job_name: 'jmx-exporter'
    static_configs:
    - targets: ['10.237.54.244:7777']

  - job_name: 'elasticsearch-exporter'
    static_configs:
    - targets: ['10.237.55.55:9108']
    - targets: ['10.211.104.103:9108']

  - job_name: 'node'
    file_sd_configs:
    - files:
      - './config/node/*.json'
      refresh_interval: 30s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - http://monitor.jdcloud.com
        - http://test.monitor.jdcloud.com
        - http://status.jdcloud.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.19.17.58:9115 

  - job_name: 'tomcat-exporter'
    file_sd_configs:
    - files:
      - './config/tomcat/*.json'
      refresh_interval: 30s

  - job_name: federate
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
        - '{__name__=~"[a-z,A-Z].*"}'   # Request all job-level time series
    static_configs:
      - targets:
        - 172.19.10.32:30003
  - job_name: 'grafana'
    static_configs:
    - targets: ['10.211.106.12:3000']
    - targets: ['10.211.105.167:3000']
